PARAMS:
  use_pubchem_cache: true
  update_pubchem_cache: false

COMPOUNDS:
    HILICZ:
      POS:
        PATHS:
          - /pscratch/sd/b/bkieft/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv
          - /pscratch/sd/b/bkieft/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv
          - /pscratch/sd/b/bkieft/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv
      NEG:
        PATHS:
         - /pscratch/sd/b/bkieft/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_ISTD_NEG.tsv
         - /pscratch/sd/b/bkieft/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_EMA_NEG.tsv
    C18:
      POS:
        PATHS:
          -
      NEG:
        PATHS:
          -