ENV:
  PATHS:
    main_database: /Users/BKieft/Metabolomics/metatlas_lite_data/databases/metatlas.duckdb

ATLASES:
  HILICZ:
    POS:
      QC:
        path: /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv
        name: Default HILICZ QC Atlas Positive
        desc: Default QC compounds used for RT alignment
      ISTD:
        path: /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv
        name: Default HILICZ ISTD Atlas Positive
        desc: Default internal standard compounds used for checking performance
      EMA:
        path: /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv
        name: Default HILICZ EMA Atlas Positive
        desc: Default experimental compounds used for targeted analysis
    NEG:
      QC:
        path:
        name:
        desc:
      ISTD:
        path:
        name:
        desc:
      EMA:
        path:
        name:
        desc:
  C18:
    POS:
      QC:
        path:
        name:
        desc:
      ISTD:
        path:
        name:
        desc:
      EMA:
        path:
        name:
        desc:
    NEG:
      QC:
        path:
        name:
        desc:
      ISTD:
        path:
        name:
        desc:
      EMA:
        path:
        name:
        desc: