paths:
  main_database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb

atlases:
  qc:
    atlas_table_path: /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv
    atlas_name: HILICZ QC Atlas Positive
    atlas_description: Default QC compounds for HILIC positive mode analysis
  istd:
    atlas_table_path: /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv
    atlas_name: HILICZ ISTD Atlas Positive
    atlas_description: Default internal standard compounds for HILIC positive mode analysis
  ema:
    atlas_table_path: /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv
    atlas_name: HILICZ EMA Atlas Positive
    atlas_description: Experimental compounds for HILIC positive mode analysis