ENV:
  PATHS:
    main_database: /Users/BKieft/Metabolomics/metatlas_lite_data/databases/metatlas.duckdb
    pubchem_cache: /Users/BKieft/Metabolomics/metatlas_lite_data/databases/pubchem_cache/pubchem_global_cache.parquet

PARAMS:
  use_pubchem_cache: true
  update_pubchem_cache: false

COMPOUNDS:
    HILICZ:
      POS:
        PATHS:
          - /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv
          - /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv
          - /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv
      NEG:
        PATHS:
         - /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_ISTD_NEG.tsv
         - /Users/BKieft/Metabolomics/metatlas_lite_data/atlas_tables/HILICZ/HILICZ_EMA_NEG.tsv
    C18:
      POS:
        PATHS:
          -
      NEG:
        PATHS:
          -