paths:
  projects_dir: /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects
  main_database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
  msms_refs: /Users/BKieft/Metabolomics/metatlas2/data/databases/msms_refs/msms_refs_no_inosine15n.tab
  pubchem_cache: /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl

rt_alignment:
  tolerances:
    i: 10000.0 # Minimum intensity to consider a QC compound peak
    mz: 20.0 # MZ tolerance to find QC compounds
    rt: 1.0 # RT window expansion to find QC compounds
  model:
    polynomial_degree: 2
    min_observations_per_compound: 1
    min_compounds_for_modeling: 2
    r2_threshold: 0.7
    exclude_inchikeys:
      - OVRNDRQMDRJTHS-ZEUBEQSHSA-N

analysis_settings:
  default_ppm_error: 5.0
  min_peak_intensity: 100000.0
  extra_time: 0.0
  ms2_min_score: 0.1
  ms2_min_matches: 2

database_options:
  overwrite_existing_main_db: true
  overwrite_existing_project_db: true
  add_compound_duplicates: false
  force_pubchem_cache_update: false

plot_settings:
  file_color_mapping:
    ISTD: blue
    ExCtrl: red
    InjBl: orange